# Python Fundamentals Accelerated - Part 2

## 2.0 Part 2: Collections and Loops
Python has several built-in objects for holding other objects (including all the things we may use as **data**). These objects are called **containers** and **collections**. While these two words may mean slightly different things in computer programming, the distinctions are small in Python and they are often used interchangeably.
Loops provide the power of Python. We can move through the objects in a container, filter based on custom conditions, and perform code on each piece of data exactly how we'd like. Unlike more functional programming languages, like R for example, Python is designed for messy data (including data that is being inputted by users in real time).
### Objects in Part 2
- Lists
- Tuples
- Sets
- Ranges
- Dictionaries

### Functions in Part 2
- List functions
- Dictionary functions

### Concepts in Part 2
- mutable vs immutable objects
- `for` loops
- `if` statements
- basic error handling

## 2.1 Lists

**A list is a collection of objects kept in a strict order. A list is surrounded by square brackets. Items in the list are separated by commas.**

A list can contain any type of object:

In [1]:
A list can contain any type of object:

*Remember that when we assign variables, nothing is returned.*

In [4]:
*Remember that when we assign variables, nothing is returned.*

*Notice that using square brackets is all that you need to tell Python that you are creating a list. You do not need to use a function.*

In [7]:
*Notice that using square brackets is all that you need to tell Python that you are creating a list. You do not need to use a function.*

list

A list can also contain only one item:

In [10]:
A list can also contain only one item:

A list can be empty:

In [12]:
A list can be empty:

A list can contain a mix of object types:

In [15]:
A list can contain a mix of object types:

You can even have a list of lists, called a **nested list**:

In [18]:
You can even have a list of lists, called a **nested list**:

### Exercise: List syntax

Create a new variable called `family` and store the names of your family members as a list (or choose your favorite TV family!). Don't forget that each name should be stored as a string.

In [20]:
Create a new variable called `family` and store the names of your family members as a list (or choose your favorite TV family!). Don't forget that each name should be stored as a string.

In [22]:
Create a new variable called `family` and store the names of your family members as a list (or choose your favorite TV family!). Don't forget that each name should be stored as a string.

['Bob', 'Linda', 'Tina', 'Gene', 'Louise']

## 2.2 Mutable vs. immutable objects

Let's learn some list functions. While we're learning list functions, we'll also learn a bit about how the list object works.

As a review, there are two types of functions: 
1. those that take a list as an argument and do something *with* the list
2. methods that follow the list and do something *to* the list

In [24]:
## 2.2 Mutable vs. immutable objects

Let's learn some list functions. While we're learning list functions, we'll also learn a bit about how the list object works.

As a review, there are two types of functions: 
1. those that take a list as an argument and do something *with* the list
2. methods that follow the list and do something *to* the list

The `len()` function that we learned with strings also works with lists:

In [27]:
The `len()` function that we learned with strings also works with lists:

7

The `sort()` method:

In [30]:
The `sort()` method:

Hmm, nothing was returned.

In [33]:
Hmm, nothing was returned.

[64, 75, 80, 88, 93, 98, 100]

Uh oh. Our list has changed order. **Unlike strings, list methods can change the list object even if you didn't save the changed object as a new variable.** This is because lists are **mutable** objects, whereas strings, integers, floats, and booleans are **immutable** objects.

*Be careful with list methods, as they will change your object!* We'll talk more about how to get around this later in this lecture. We'll also see why it's useful to have lists be mutable.

The `append()` method will add a new item to the end of a list:

In [38]:
The `append()` method will add a new item to the end of a list:

In [40]:
The `append()` method will add a new item to the end of a list:

Just like all objects, you can return the variable value by either just running the name of the variable:

In [43]:
Just like all objects, you can return the variable value by either just running the name of the variable:

['Alex', 'Billy', 'Casey', 'Drake', 'Ellis', 'Frankie', 'Gavi']

Or by printing the variable:

In [46]:
Or by printing the variable:

['Alex', 'Billy', 'Casey', 'Drake', 'Ellis', 'Frankie', 'Gavi']

Regular functions (not methods) will not change your list, because they do something *with* your object, not something *to* your object. The `sum()` function will give you the sum of a list of numbers:

In [49]:
Regular functions (not methods) will not change your list, because they do something *with* your object, not something *to* your object. The `sum()` function will give you the sum of a list of numbers:

In [51]:
Regular functions (not methods) will not change your list, because they do something *with* your object, not something *to* your object. The `sum()` function will give you the sum of a list of numbers:

598

In [53]:
Regular functions (not methods) will not change your list, because they do something *with* your object, not something *to* your object. The `sum()` function will give you the sum of a list of numbers:

[93, 75, 80, 98, 100, 64, 88]

### Exercise: List functions

Run the cell below to store the list `colors`. Write code to append a new color of your choice to the list `colors`. Then write code to return the length of the list.

In [57]:
Run the cell below to store the list `colors`. Write code to append a new color of your choice to the list `colors`. Then write code to return the length of the list.

In [59]:
Run the cell below to store the list `colors`. Write code to append a new color of your choice to the list `colors`. Then write code to return the length of the list.

In [61]:
Run the cell below to store the list `colors`. Write code to append a new color of your choice to the list `colors`. Then write code to return the length of the list.

5

## 2.3 More list functions

We are going to use some list functions in this notebook that aren't automatically loaded with Python. They are in a module that is included with Python, called `statistics`.

Run this cell to import the `statistics` module:

In [63]:
Run this cell to import the `statistics` module:

We already learned some list functions. Let's make a list of banana bunches. Each number in the list represents the number of bananas in one bunch.

In [66]:
We already learned some list functions. Let's make a list of banana bunches. Each number in the list represents the number of bananas in one bunch.

`sum()`:

In [69]:
`sum()`:

33

`len()`:

In [72]:
`len()`:

6

`append()`:

In [75]:
`append()`:

[4, 9, 7, 4, 3, 6, 8]

`sort()`:

In [78]:
`sort()`:

[3, 4, 4, 6, 7, 8, 9]

We can also pass a **keyword argument** to the `sort()` function to reverse the sort order of the list:

In [81]:
We can also pass a **keyword argument** to the `sort()` function to reverse the sort order of the list:

[9, 8, 7, 6, 4, 4, 3]

As a reminder, we need to pass a **keyword argument** to change a parameter that has a default value. If you want to use something other than the default value, you have to pass the function the keyword with the new value. So for `sort()` the default of the `reverse` argument is `False`. When we want to reverse it, we need to change `reverse` to `True` by passing it as an argument.

**More built-in functions**

In [85]:
**More built-in functions**

3

In [87]:
**More built-in functions**

9

As a reminder, to use a function from an imported module, you type the name of the module followed by `.` followed by the name of the function. Let's use `statistics.mean()`:

In [90]:
As a reminder, to use a function from an imported module, you type the name of the module followed by `.` followed by the name of the function. Let's use `statistics.mean()`:

5.857142857142857

`statistics.median()`:

In [93]:
`statistics.median()`:

6

### Exercise: Finding list functions

Let's practice finding information online. Use Google (or ChatGPT, if that's already your default search) to search for the correct Python function to calculate standard deviation, and then write the code to find the standard deviation of `bananas_in_bunches`:

In [95]:
Let's practice finding information online. Use Google (or ChatGPT, if that's already your default search) to search for the correct Python function to calculate standard deviation, and then write the code to find the standard deviation of `bananas_in_bunches`:

In [101]:
Let's practice finding information online. Use Google (or ChatGPT, if that's already your default search) to search for the correct Python function to calculate standard deviation, and then write the code to find the standard deviation of `bananas_in_bunches`:

2.258317958127243

## 2.4 List operators

We can use comparison operators with lists, just like other objects:

In [105]:
We can use comparison operators with lists, just like other objects:

In [107]:
We can use comparison operators with lists, just like other objects:

False

In [109]:
We can use comparison operators with lists, just like other objects:

False

We can use some arithmetic operators with lists:

In [112]:
We can use some arithmetic operators with lists:

In [114]:
We can use some arithmetic operators with lists:

[93, 75, 80, 98, 100, 64, 88, 70, 93]

In [116]:
We can use some arithmetic operators with lists:

TypeError: unsupported operand type(s) for -: 'list' and 'list'

You can't subtract lists!

In [119]:
You can't subtract lists!

[93, 75, 80, 98, 100, 64, 88, 70, 93, 93, 75, 80, 98, 100, 64, 88, 70, 93, 93, 75, 80, 98, 100, 64, 88, 70, 93, 93, 75, 80, 98, 100, 64, 88, 70, 93]

In [121]:
You can't subtract lists!

[93, 75, 80, 98, 100, 64, 88, 70, 93]

## 2.5 List indexing

Indexing works just like it does in strings (the first item is indexed as 0).

In [125]:
Indexing works just like it does in strings (the first item is indexed as 0).

In [127]:
Indexing works just like it does in strings (the first item is indexed as 0).

'Alex'

We can use negative indexing with lists.

In [130]:
We can use negative indexing with lists.

'Ellis'

We can take a sublist from a list.

In [133]:
We can take a sublist from a list.

['Billy', 'Casey', 'Drake']

We can change the value of individual items in a list using indexing.

In [136]:
We can change the value of individual items in a list using indexing.

['Alex', 'Billy', 'Casey', 'Drake', 'Ellis', 'Frankie']

To change Billy to Billie, I can assign the new string "Billie" to "Billy"'s indexed position in the list:

In [139]:
To change Billy to Billie, I can assign the new string "Billie" to "Billy"'s indexed position in the list:

In [141]:
To change Billy to Billie, I can assign the new string "Billie" to "Billy"'s indexed position in the list:

['Alex', 'Billie', 'Casey', 'Drake', 'Ellis', 'Frankie']

### Exercise: List indexing

Run the code cell below to store the list `states`. Write code to change "Illinois" to "Indiana".

In [145]:
Run the code cell below to store the list `states`. Write code to change "Illinois" to "Indiana".

In [147]:
Run the code cell below to store the list `states`. Write code to change "Illinois" to "Indiana".

In [ ]:
Run the code cell below to store the list `states`. Write code to change "Illinois" to "Indiana".

In [150]:
Run the code cell below to store the list `states`. Write code to change "Illinois" to "Indiana".

['Hawaii', 'Kentucky', 'Indiana', 'Iowa']

You can also use a `for loop` to make lots of different changes to a list, which we will learn later.

## 2.6 Indexing multiple levels

You can index characters inside a string inside a list. Like this:

In [152]:
You can index characters inside a string inside a list. Like this:

My first name starts with C.

Indexing starts on the outermost level and works its way in. So in the next line of code, the first item indexed, `[2]`, is selecting which item in the list. The second item indexed, `[1:3]`, is selecting the substring of characters from that item.

In [155]:
Indexing starts on the outermost level and works its way in. So in the next line of code, the first item indexed, `[2]`, is selecting which item in the list. The second item indexed, `[1:3]`, is selecting the substring of characters from that item.

'oo'

You would use the same style of indexing to index items inside a **nested list**:

In [158]:
You would use the same style of indexing to index items inside a **nested list**:

Try to guess what will be returned before you run the following cells.

In [161]:
Try to guess what will be returned before you run the following cells.

'Mae'

In [163]:
Try to guess what will be returned before you run the following cells.

88

In [165]:
Try to guess what will be returned before you run the following cells.

'y'

### Exercise: Indexing Multiple Levels

Write your own name as a list of your first, middle, and last names (or however many names you have):

In [167]:
Write your own name as a list of your first, middle, and last names (or however many names you have):

Write code to index the last letter of your first name:

In [170]:
Write code to index the last letter of your first name:

'y'

You ran an experiment 5 times a day for 3 days. These are your results:

In [173]:
You ran an experiment 5 times a day for 3 days. These are your results:

What is the value of the very last run on the last day?

In [176]:
What is the value of the very last run on the last day?

0.776

What is the minimum value you obtained on the first day of your experiment?

In [178]:
What is the minimum value you obtained on the first day of your experiment?

0.001

What is the mean of the values you obtained on your second day?

In [180]:
What is the mean of the values you obtained on your second day?

0.6966

## 2.7 More about mutable objects

### Exercise - Code along to learn more about lists

If you want more practice typing code, follow along with me. Otherwise, just watch me code and try to spot what I do differently between example 1 and example 2.

Example 1

In [182]:
Example 1

In [184]:
Example 1

In [186]:
Example 1

['hobbit']

In [188]:
Example 1

['hobbit']

In [190]:
Example 1

In [192]:
Example 1

['hobbit', 'ring']

In [194]:
Example 1

['hobbit', 'ring']

In [ ]:
Example 1

In [ ]:
Example 1

In [ ]:
Example 1

Example 2

In [206]:
Example 2

In [208]:
Example 2

In [210]:
Example 2

['wizard']

In [212]:
Example 2

['wizard']

In [214]:
Example 2

In [216]:
Example 2

['wizard', 'scar']

In [218]:
Example 2

['wizard']

In [ ]:
Example 2

In [ ]:
Example 2

**What did we do differently between example 1 and example 2?**

Example 3

In [222]:
Example 3

In [224]:
Example 3

In [226]:
Example 3

['hobbit']

In [228]:
Example 3

['hobbit']

In [230]:
Example 3

In [232]:
Example 3

['hobbit', 'ring']

In [234]:
Example 3

['hobbit']

In [ ]:
Example 3

In [ ]:
Example 3

## 2.8 Joining items in a list into one string

Sometimes you will need to join the items in a list together into a string.

In [236]:
Sometimes you will need to join the items in a list together into a string.

The `join()` function is actually a string method. The string you start with is the string that you want to use to connect all the items in the list. Then you pass the list to the function as an argument:

In [239]:
The `join()` function is actually a string method. The string you start with is the string that you want to use to connect all the items in the list. Then you pass the list to the function as an argument:

'Bartholomew JoJo Simpson'

In [241]:
The `join()` function is actually a string method. The string you start with is the string that you want to use to connect all the items in the list. Then you pass the list to the function as an argument:

'Bartholomew-JoJo-Simpson'

In [243]:
The `join()` function is actually a string method. The string you start with is the string that you want to use to connect all the items in the list. Then you pass the list to the function as an argument:

'BartholomewDOHJoJoDOHSimpson'

You can use an empty string to connect all the items in the list with nothing in between:

In [246]:
You can use an empty string to connect all the items in the list with nothing in between:

'BartholomewJoJoSimpson'

### Exercise: Joining a list into a string

In [248]:
### Exercise: Joining a list into a string

Use the join function to combine these words into one string. The words should be separated by a "/" to create a file path.

In [250]:
Use the join function to combine these words into one string. The words should be separated by a "/" to create a file path.

'Documents/workshops/bootcamp/tuesday/tuesdayLecture.ipynb'

*Bonus exercise*: Join the path_list together with a "\\" for a Windows computer. Does it behave as you expected? Can you think of a solution?

In [254]:
*Bonus exercise*: Join the path_list together with a "\\" for a Windows computer. Does it behave as you expected? Can you think of a solution?

'Documents\\workshops\\bootcamp\\tuesday\\tuesdayLecture.ipynb'

In [256]:
*Bonus exercise*: Join the path_list together with a "\\" for a Windows computer. Does it behave as you expected? Can you think of a solution?

Documents\workshops\bootcamp\tuesday\tuesdayLecture.ipynb

## 2.9 Splitting a string into a list

Another common task is splitting a string into a list. This is also a string method, so let's load a string to practice with:

In [258]:
Another common task is splitting a string into a list. This is also a string method, so let's load a string to practice with:

You must pass the `split()` function an argument - what string do you want to use to separate the items for your list. Here we'll use a comma:

In [261]:
You must pass the `split()` function an argument - what string do you want to use to separate the items for your list. Here we'll use a comma:

['sample 1', '5', '24', '864', 'NA', '.4556', '', '', '65']

### Exercise: Splitting a string

In [263]:
### Exercise: Splitting a string

Run the cell above. We want to turn the string `my_data` into a list of years, without any other text or new lines.
First, write code to remove every occurrence of "Year: " from the string. You'll have to remember a string function you learned yesterday:

In [267]:
Run the cell above. We want to turn the string `my_data` into a list of years, without any other text or new lines.
First, write code to remove every occurrence of "Year: " from the string. You'll have to remember a string function you learned yesterday:

2005
2007
2010
2011
2015

Now, write code to split the string into a list of years:

In [269]:
Now, write code to split the string into a list of years:

['2005', '2007', '2010', '2011', '2015']

*Challenge:* Change `my_data` into a list of years again, but this time do it in only one line of code:

In [271]:
*Challenge:* Change `my_data` into a list of years again, but this time do it in only one line of code:

['2005', '2007', '2010', '2011', '2015']

## 2.10 for loops

Before we start coding with "for loops", let's talk about how they work - **DEMO in the slides**

We're going to work with a list of student grades.

In [273]:
We're going to work with a list of student grades.

When writing the for loop, the lines **inside** the loop are indented. You can use four spaces or one tab to indent. Jupyter Lab, Google Colab, and many other Python IDEs will automatically change a tab into four spaces. This is because all the indentations in a script have to match - when using **scripts** you can only use all tabs or all spaces or else you'll get an error - so the IDE does the work for you of making everything match as spaces. *However, when writing scripts in a text editor, you'll need to do the work yourself and make sure they all match*. If you ever watched the show Silicon Valley, now you can understand this scene: https://www.youtube.com/watch?v=cowtgmZuai0.

In [276]:
When writing the for loop, the lines **inside** the loop are indented. You can use four spaces or one tab to indent. Jupyter Lab, Google Colab, and many other Python IDEs will automatically change a tab into four spaces. This is because all the indentations in a script have to match - when using **scripts** you can only use all tabs or all spaces or else you'll get an error - so the IDE does the work for you of making everything match as spaces. *However, when writing scripts in a text editor, you'll need to do the work yourself and make sure they all match*. If you ever watched the show Silicon Valley, now you can understand this scene: https://www.youtube.com/watch?v=cowtgmZuai0.

73
64
89
93
59
100
79

*Notice that the items are printed in the same order as the list.*

We can change the name of our temporary variable:

In [280]:
We can change the name of our temporary variable:

73
64
89
93
59
100
79

In [282]:
We can change the name of our temporary variable:

73
64
89
93
59
100
79

Let's say we want to give each student an extra 5 points:

In [285]:
Let's say we want to give each student an extra 5 points:

78
69
94
98
64
105
84

### Exercise: for loop syntax

Run the following cell to store a list of coding languages.

In [289]:
Run the following cell to store a list of coding languages.

Write a for loop to print each item in the `languages` list.

*Be prepared for the IDE to automatically indent the line under your for loop.*

In [293]:
*Be prepared for the IDE to automatically indent the line under your for loop.*

Python
R
JavaScript
Julia
Swift
C#
PHP
BASIC
C++
Java

#### Some common loop errors

Can you see the problem with each of these loops?

In [295]:
Can you see the problem with each of these loops?

NameError: name 'y' is not defined

In [297]:
Can you see the problem with each of these loops?

SyntaxError: expected ':' (205954698.py, line 1)

In [299]:
Can you see the problem with each of these loops?

IndentationError: expected an indented block after 'for' statement on line 1 (972508709.py, line 2)

## 2.11 if statements

These are also called **conditional statements** or even **conditionals**. Try to predict what will happen when you run these code cells:

In [301]:
These are also called **conditional statements** or even **conditionals**. Try to predict what will happen when you run these code cells:

In [303]:
These are also called **conditional statements** or even **conditionals**. Try to predict what will happen when you run these code cells:

That seems right.

In [305]:
These are also called **conditional statements** or even **conditionals**. Try to predict what will happen when you run these code cells:

Hmmm... That seems wrong.

**if statements** are often used with for loops to filter data for different conditions.

In [307]:
**if statements** are often used with for loops to filter data for different conditions.

We can use a series of if/elif/else statements to perform different actions on grades in different ranges:

In [310]:
We can use a series of if/elif/else statements to perform different actions on grades in different ranges:

73
grade is C
64
grade is D
89
grade is B
93
grade is A
59
grade is Fail
100
grade is A
79
grade is C

Here we are going to print only grades that are 60 or higher:

In [313]:
Here we are going to print only grades that are 60 or higher:

73
64
89
93
100
79

We don't have to explicitly pass if the condition isn't met. **You do not need to include an `else` statement.**

In [316]:
We don't have to explicitly pass if the condition isn't met. **You do not need to include an `else` statement.**

73
64
89
93
100
79

### Exercise: Writing if statements

Store this list of Therapod dinosaurs (meat eaters that walk on two legs).

In [318]:
Store this list of Therapod dinosaurs (meat eaters that walk on two legs).

*Note: When typing a long list, you can use multiple lines. Try to line up the next line with the first item in the list.*

Loop through the list `therapods`. Use string indexing to check **if** the first letter of the dinosaur's name is equal to T. If it is T, print the dinosaur's name. If it is not T, print "Not T".

In [320]:
Loop through the list `therapods`. Use string indexing to check **if** the first letter of the dinosaur's name is equal to T. If it is T, print the dinosaur's name. If it is not T, print "Not T".

Not T
Not T
Not T
Not T
Not T
Not T
Not T
Not T
Not T
Not T
Not T
Not T
Not T
Tyrannosaurus
Tyrannotitan
Not T
Not T

## 2.12 Breaking a loop 
We can also stop the loop if a condition is or isn't met:

In [322]:
## 2.12 Breaking a loop 
We can also stop the loop if a condition is or isn't met:

[73, 64, 89, 93, 59, 100, 79]

In [324]:
## 2.12 Breaking a loop 
We can also stop the loop if a condition is or isn't met:

This student is doing ok.
I give up. I quit.

Here I'm switching the order of the last two lines. Take a minute to try and predict what will happen before running the code.

In [327]:
Here I'm switching the order of the last two lines. Take a minute to try and predict what will happen before running the code.

This student is doing ok.

## 2.13 The in operator
#### New boolean operator

So far we've learned `` `=` `==` and `!=`.

`in` is another Boolean operator. It works for both lists and strings. Take a minute to predict if each boolean statement will return True or False before you run the cell.

In [332]:
`in` is another Boolean operator. It works for both lists and strings. Take a minute to predict if each boolean statement will return True or False before you run the cell.

True

In [334]:
`in` is another Boolean operator. It works for both lists and strings. Take a minute to predict if each boolean statement will return True or False before you run the cell.

True

In [336]:
`in` is another Boolean operator. It works for both lists and strings. Take a minute to predict if each boolean statement will return True or False before you run the cell.

True

In [338]:
`in` is another Boolean operator. It works for both lists and strings. Take a minute to predict if each boolean statement will return True or False before you run the cell.

False

In [340]:
`in` is another Boolean operator. It works for both lists and strings. Take a minute to predict if each boolean statement will return True or False before you run the cell.

True

In [342]:
`in` is another Boolean operator. It works for both lists and strings. Take a minute to predict if each boolean statement will return True or False before you run the cell.

False

We can use the `in` comparison operator with if statements.

In [345]:
We can use the `in` comparison operator with if statements.

Chips Ahoy

Let's say we want to give one extra point to anyone who is right on the cusp of getting a better grade:

In [348]:
Let's say we want to give one extra point to anyone who is right on the cusp of getting a better grade:

We'll loop through the `grades` list. If the grade is in the `grades_to_round` list, we'll add one point to the grade. If the grade is not in `grades_to_round`, we'll print the original grade.

In [351]:
We'll loop through the `grades` list. If the grade is in the `grades_to_round` list, we'll add one point to the grade. If the grade is not in `grades_to_round`, we'll print the original grade.

73
64
90
93
60
100
80

There's also `not in`:

In [354]:
There's also `not in`:

73
64
90
93
60
100
80

If you want your code to run faster, you should think about when to use `in` vs. `not in`. If you think the majority of the items in your loop will be `in`, you should put that condition in the `if` statement. If you think the majority of the items in your loop will be `not in`, you should put that condition in the `if` statement. This is because once the condition is met for an item, the computer does not need to read any following `elif` or `else` statements, saving a bit of time.

### Exercise: The `in` boolean

Make a list of the toppings you like to eat on your ideal pizza (don't forget to run the cell):

In [356]:
Make a list of the toppings you like to eat on your ideal pizza (don't forget to run the cell):

Run the cell below to store a list of toppings that are available at the store.

In [359]:
Run the cell below to store a list of toppings that are available at the store.

Loop through the `my_toppings` list. If the topping is also in the `store_toppings` list, print out a message saying that the topping is available. If the topping in your list is not available at the store, print out a message telling you that the topping isn't available.

In [361]:
Loop through the `my_toppings` list. If the topping is also in the `store_toppings` list, print out a message saying that the topping is available. If the topping in your list is not available at the store, print out a message telling you that the topping isn't available.

garlic is available.
pepperoni is available.
cicadas is not available.

In [ ]:
Loop through the `my_toppings` list. If the topping is also in the `store_toppings` list, print out a message saying that the topping is available. If the topping in your list is not available at the store, print out a message telling you that the topping isn't available.

## 2.14 Basic error handling

**Short DEMO in the slides.** You will get more practice with try/except later.

## 2.15 More list practice

### Exercise: Indexing lists

In [363]:
### Exercise: Indexing lists

*Note: When typing a long list, you can use multiple lines. Try to line up the next line with the first item in the list.*

#### Run the line of code above. Use list indexing to answer these questions:

Which month has your favorite holiday?

In [368]:
Which month has your favorite holiday?

'December'

Which months do you consider to be part of Summer?

In [372]:
Which months do you consider to be part of Summer?

['June', 'July', 'August', 'September']

What month were you born? Try to print out your answer in a complete sentence that includes your indexed month.

In [374]:
What month were you born? Try to print out your answer in a complete sentence that includes your indexed month.

'July'

### Exercise: Comparisons between lists

In [376]:
### Exercise: Comparisons between lists

Based on the lists above, will the following booleans evaluate to True or False? Try to answer before running the code to check:

In [379]:
Based on the lists above, will the following booleans evaluate to True or False? Try to answer before running the code to check:

False

In [381]:
Based on the lists above, will the following booleans evaluate to True or False? Try to answer before running the code to check:

False

In [383]:
Based on the lists above, will the following booleans evaluate to True or False? Try to answer before running the code to check:

False

### Exercise: List functions

Check out all of the list method functions at this link:
[https://docs.python.org/3/tutorial/datastructures.html](https://docs.python.org/3/tutorial/datastructures.html)
Choose at least one list method from the website that we haven't learned yet. Create a list of anything to practice with, and then try out your chosen list method function to see how it works.

In [ ]:
Check out all of the list method functions at this link:
[https://docs.python.org/3/tutorial/datastructures.html](https://docs.python.org/3/tutorial/datastructures.html)
Choose at least one list method from the website that we haven't learned yet. Create a list of anything to practice with, and then try out your chosen list method function to see how it works.

In [ ]:
Check out all of the list method functions at this link:
[https://docs.python.org/3/tutorial/datastructures.html](https://docs.python.org/3/tutorial/datastructures.html)
Choose at least one list method from the website that we haven't learned yet. Create a list of anything to practice with, and then try out your chosen list method function to see how it works.

In [ ]:
Check out all of the list method functions at this link:
[https://docs.python.org/3/tutorial/datastructures.html](https://docs.python.org/3/tutorial/datastructures.html)
Choose at least one list method from the website that we haven't learned yet. Create a list of anything to practice with, and then try out your chosen list method function to see how it works.

In [ ]:
Check out all of the list method functions at this link:
[https://docs.python.org/3/tutorial/datastructures.html](https://docs.python.org/3/tutorial/datastructures.html)
Choose at least one list method from the website that we haven't learned yet. Create a list of anything to practice with, and then try out your chosen list method function to see how it works.

## 2.16 Adding items to an empty list

**LOGIC** *This is a very common task in Python.*

We'll start with a list of grades. Then, let's create a new list of grades, giving everyone 5 extra points. Run this cell to save our list of grades:

In [385]:
We'll start with a list of grades. Then, let's create a new list of grades, giving everyone 5 extra points. Run this cell to save our list of grades:

First, we create a new **empty list**.

In [388]:
First, we create a new **empty list**.

Then we loop through our original list and **append** the changed items to our new list.

In [391]:
Then we loop through our original list and **append** the changed items to our new list.

In [393]:
Then we loop through our original list and **append** the changed items to our new list.

[78, 69, 94, 98, 64, 105, 84]

If you are working with more complicated calculations, you will want to be more **explicit** by defining a new variable inside the loop instead of doing the calculations inside the `append()` function:

In [396]:
If you are working with more complicated calculations, you will want to be more **explicit** by defining a new variable inside the loop instead of doing the calculations inside the `append()` function:

In [398]:
If you are working with more complicated calculations, you will want to be more **explicit** by defining a new variable inside the loop instead of doing the calculations inside the `append()` function:

In [400]:
If you are working with more complicated calculations, you will want to be more **explicit** by defining a new variable inside the loop instead of doing the calculations inside the `append()` function:

[0.78, 0.69, 0.94, 0.98, 0.64, 1.05, 0.84]

There's one more thing we should consider. Go up and rerun the code cell with the `for loop` one more time. Then run the cell where we print the value of `new_grades`. Do this a few times and you'll see that there's a problem. Every time we rerun the loop, it's just adding the new grades to that same list.
Because we're not recreating the empty list in the same code cell as the `for loop`, it's easy to forget to rerun the `new_grades = []` cell every time we run our loop. Especially when we're testing out our code. To prevent this, we should include the creation of the empty list in the same code cell as the `for loop`, like this:

In [403]:
There's one more thing we should consider. Go up and rerun the code cell with the `for loop` one more time. Then run the cell where we print the value of `new_grades`. Do this a few times and you'll see that there's a problem. Every time we rerun the loop, it's just adding the new grades to that same list.
Because we're not recreating the empty list in the same code cell as the `for loop`, it's easy to forget to rerun the `new_grades = []` cell every time we run our loop. Especially when we're testing out our code. To prevent this, we should include the creation of the empty list in the same code cell as the `for loop`, like this:

In [405]:
There's one more thing we should consider. Go up and rerun the code cell with the `for loop` one more time. Then run the cell where we print the value of `new_grades`. Do this a few times and you'll see that there's a problem. Every time we rerun the loop, it's just adding the new grades to that same list.
Because we're not recreating the empty list in the same code cell as the `for loop`, it's easy to forget to rerun the `new_grades = []` cell every time we run our loop. Especially when we're testing out our code. To prevent this, we should include the creation of the empty list in the same code cell as the `for loop`, like this:

[0.78, 0.69, 0.94, 0.98, 0.64, 1.05, 0.84]

### Exercise: Adding items to an empty list

Store this list of monthly bills that you pay:

In [409]:
Store this list of monthly bills that you pay:

First, create a new empty list called `rounded_bills`. Then, loop through the list `bills`. **For** each item in the list, **round** the item to the closest whole number and **append** it to the list `rounded_bills`.

In [412]:
First, create a new empty list called `rounded_bills`. Then, loop through the list `bills`. **For** each item in the list, **round** the item to the closest whole number and **append** it to the list `rounded_bills`.

In [414]:
First, create a new empty list called `rounded_bills`. Then, loop through the list `bills`. **For** each item in the list, **round** the item to the closest whole number and **append** it to the list `rounded_bills`.

[115, 70, 27, 171, 1250, 65]

## 2.16 More practice with loop logic

We just walked through one common situation you'll use in your own Python code - looping through a list and appending items to a new list. 
**LOGIC** Now we'll work through 4 other common situations you'll encounter. These exercises are about applying logic to solve problems - you already know all the objects, functions, and syntax needed to solve these.

### Example 1 - Doing something with each item in a list

First, let's store a list of the forecasted high temperatures on Northwestern's Qatar campus for this coming week:

In [425]:
First, let's store a list of the forecasted high temperatures on Northwestern's Qatar campus for this coming week:

The equation to convert from Celsius to Farenheit is F = C x 9/5 + 32. 
We can write a for loop to convert our `c_temps` to Farenheit:

In [428]:
The equation to convert from Celsius to Farenheit is F = C x 9/5 + 32. 
We can write a for loop to convert our `c_temps` to Farenheit:

91.4
95.0
102.2
98.60000000000001
100.4
96.8
96.8

Let's improve this output by rounding the temperatures to one digit past the decimal, and by writing a complete sentence:

In [431]:
Let's improve this output by rounding the temperatures to one digit past the decimal, and by writing a complete sentence:

The high temperature was 91.4 degrees F (33 C).
The high temperature was 95.0 degrees F (35 C).
The high temperature was 102.2 degrees F (39 C).
The high temperature was 98.6 degrees F (37 C).
The high temperature was 100.4 degrees F (38 C).
The high temperature was 96.8 degrees F (36 C).
The high temperature was 96.8 degrees F (36 C).

### Loops Exercise 1

First, store this list. It contains the world record fastest 5K times for men and women:

In [436]:
First, store this list. It contains the world record fastest 5K times for men and women:

5 kilometers is equal to 3.10686 miles.

To convert a runner's 5K time to their 1 mile time, use the equation:
mile_time = fiveK_time / 3.10686

Write a for loop to loop through the `fastest5k` list. Inside the for loop, convert the 5K time to a mile time, round the mile time to two digits after the decimal point, and print the answer in a complete sentence.

In [439]:
Write a for loop to loop through the `fastest5k` list. Inside the for loop, convert the 5K time to a mile time, round the mile time to two digits after the decimal point, and print the answer in a complete sentence.

12.817 5k time is equivalent to a 1 mile time of 4.125387046728852.
13.9 5k time is equivalent to a 1 mile time of 4.473970503981512.

In [ ]:
Write a for loop to loop through the `fastest5k` list. Inside the for loop, convert the 5K time to a mile time, round the mile time to two digits after the decimal point, and print the answer in a complete sentence.

In [ ]:
Write a for loop to loop through the `fastest5k` list. Inside the for loop, convert the 5K time to a mile time, round the mile time to two digits after the decimal point, and print the answer in a complete sentence.

### Example 2 - Using all the items in the list to find one number

This list contains the names of students in your class:

In [441]:
This list contains the names of students in your class:

On your classroom wall, you want to spell out all of the students' names with one letter per piece of paper, but you need to know how many pieces of paper you need. Luckily, the `len()` function will tell you how many letters are in each name, but you need to tally up the total.

To do this, you are first going to assign the number zero to a variable:

In [445]:
To do this, you are first going to assign the number zero to a variable:

Next, you can loop through the list, adding the length of each name to your `papers` variable as you go:

In [448]:
Next, you can loop through the list, adding the length of each name to your `papers` variable as you go:

Let's see if it worked:

In [451]:
Let's see if it worked:

28

This is a common situation that comes up when you're coding, so it's good to practice it now.

Remember the lesson we learned earlier today when we created an empty list in a code cell outside the cell where we wrote our `for loop`? Go up and rerun the cell with our `for loop` and then the cell where we print `papers`.
Oops! We forgot to reset `papers` to 0 before rerunning the `for loop`. We should have written the code in one cell:

In [455]:
Remember the lesson we learned earlier today when we created an empty list in a code cell outside the cell where we wrote our `for loop`? Go up and rerun the cell with our `for loop` and then the cell where we print `papers`.
Oops! We forgot to reset `papers` to 0 before rerunning the `for loop`. We should have written the code in one cell:

28

### Loops Exercise 2

Run the cell below to store a list of birds you observed at the bird feeder outside your window:

In [459]:
Run the cell below to store a list of birds you observed at the bird feeder outside your window:

How many Red-winged Blackbirds did you see?

First create a variable called `blackbird_count` that stores the number 0. Then, write a for loop to loop through the `bird_obs` list. *If* the bird is a Red-winged Blackbird, reassign the variable `blackbird_count` to it's current value plus 1.

In [463]:
First create a variable called `blackbird_count` that stores the number 0. Then, write a for loop to loop through the `bird_obs` list. *If* the bird is a Red-winged Blackbird, reassign the variable `blackbird_count` to it's current value plus 1.

Now print the variable `blackbird_count`:

In [465]:
Now print the variable `blackbird_count`:

8

### Example 3 - Using a for loop with if/elif/else statements to filter the items in a list.

In [467]:
### Example 3 - Using a for loop with if/elif/else statements to filter the items in a list.

In [469]:
### Example 3 - Using a for loop with if/elif/else statements to filter the items in a list.

I'm not sure who this student is, they just showed up one day.
Dustin can move up to 8th grade.
Mike can move up to 8th grade.
Will should repeat 7th grade because of absences.
Lucas can move up to 8th grade.
Max can move up to 8th grade.

We can add more code under each if/elif/else statement. Let's add the students to the correct empty list:

In [472]:
We can add more code under each if/elif/else statement. Let's add the students to the correct empty list:

I'm not sure who this student is, they just showed up one day.
Dustin can move up to 8th grade.
Mike can move up to 8th grade.
Will should repeat 7th grade because of absences.
Lucas can move up to 8th grade.
Max can move up to 8th grade.

In [474]:
We can add more code under each if/elif/else statement. Let's add the students to the correct empty list:

Grade 7:
['Will']
Grade 8:
['Dustin', 'Mike', 'Lucas', 'Max']
Unsure where to place:
['Eleven']

### Loops Exercise 3

*This one will take a little thought.*

In [478]:
*This one will take a little thought.*

The list `grades` shows the homework grades that one student received over the quarter. You told the students that you would drop their one lowest homework grade.

First, create a new empty list called `final_grades`. Then, write a for loop to loop through `grades`. **For** each grade in the list, **if** the grade is **not equal to** the lowest grade in the list, **append** it to `final_grades`:
*Hint: you can use the min() function to find the lowest grade in the list.*

In [481]:
First, create a new empty list called `final_grades`. Then, write a for loop to loop through `grades`. **For** each grade in the list, **if** the grade is **not equal to** the lowest grade in the list, **append** it to `final_grades`:
*Hint: you can use the min() function to find the lowest grade in the list.*

Print `final_grades`.

In [483]:
Print `final_grades`.

[90, 92, 89, 95, 94, 100, 92]

### Example 4: Using try/except to handle unexpected variations in a list

We often need to use try/except if we aren't sure whether all the items in our list are of the correct data type.

In [485]:
We often need to use try/except if we aren't sure whether all the items in our list are of the correct data type.

Let's say we want to give an extra 2 points for every test.

In [488]:
Let's say we want to give an extra 2 points for every test.

TypeError: can only concatenate str (not "int") to str

This gave us an error because you can't add the number 2 to the word "absent", so we can rewrite it:

In [491]:
This gave us an error because you can't add the number 2 to the word "absent", so we can rewrite it:

[92, 97, 'absent', 102, 78]

You need to specify the type of error in your except statement.
Sometimes this means that you need to run the code without try/except first to get the name of the error you should expect.
If you don't include the error type, it will perform the except code for all exceptions, which might seem great, but it can actually create more trouble for you down the road.

In [494]:
You need to specify the type of error in your except statement.
Sometimes this means that you need to run the code without try/except first to get the name of the error you should expect.
If you don't include the error type, it will perform the except code for all exceptions, which might seem great, but it can actually create more trouble for you down the road.

Here we have the same list, except you accidentally entered the last score as a string instead of an integer. Let's try this list with the same code we just wrote:

In [497]:
Here we have the same list, except you accidentally entered the last score as a string instead of an integer. Let's try this list with the same code we just wrote:

[92, 97, 'absent', 102, '76']

It didn't add bonus points to the last score, even though you need that score included. Let's try this to account for the last score:

In [500]:
It didn't add bonus points to the last score, even though you need that score included. Let's try this to account for the last score:

ValueError: invalid literal for int() with base 10: 'absent'

Now we can see that we get a second error, a ValueError, because Python can't convert "absent" to an integer. We can add a second try/except to our code:

In [503]:
Now we can see that we get a second error, a ValueError, because Python can't convert "absent" to an integer. We can add a second try/except to our code:

[92, 97, 'absent', 102, 78]

This was a complicated example, but it shows how it can take some logic to get the results you want.

### Loops Exercise 4

Store this list of students:

In [508]:
Store this list of students:

Run the code below to identify the error:

In [511]:
Run the code below to identify the error:

6
4
4
5

TypeError: object of type 'int' has no len()

Write a new loop to print the length of each student's name. Include a try/except block. You can decide what you want to do with 11 - pass? print something? change to a string?

In [513]:
Write a new loop to print the length of each student's name. Include a try/except block. You can decide what you want to do with 11 - pass? print something? change to a string?

6
4
4
5
2
3

In [ ]:
Write a new loop to print the length of each student's name. Include a try/except block. You can decide what you want to do with 11 - pass? print something? change to a string?

In [ ]:
Write a new loop to print the length of each student's name. Include a try/except block. You can decide what you want to do with 11 - pass? print something? change to a string?

## 2.17 Tuples

You are already familiar with tuples! You just didn't know they were called that. A tuple follows every function call:

In [515]:
You are already familiar with tuples! You just didn't know they were called that. A tuple follows every function call:

489000

(489289, -3) is a tuple.

A tuple is another Python **container**, like a list. An iterator is a collection of items kept in order that can be looped through.
A tuple is the same as a list, but it is **immutable**.

Tuples are usually designated by parentheses:

In [520]:
Tuples are usually designated by parentheses:

tuple

but, they are technically designated just by having objects separated by commas:

In [523]:
but, they are technically designated just by having objects separated by commas:

tuple

To make an empty tuple, you have to use parentheses:

In [526]:
To make an empty tuple, you have to use parentheses:

tuple

You can loop through a tuple:

In [529]:
You can loop through a tuple:

beagle
boxer
border collie

Regular functions will work on tuples:

In [532]:
Regular functions will work on tuples:

21

In [534]:
Regular functions will work on tuples:

3

Most list methods do not work with tuples:

In [537]:
Most list methods do not work with tuples:

AttributeError: 'tuple' object has no attribute 'append'

In fact, tuples have very limited methods. Tuples are mostly used behind the scenes in Python, but occasionally you will see one returned to you from a function, so it's good to recognize them.

If you remember from our first lesson in Part 1, there are special arithmetic operators for division.
Regular division:

In [541]:
If you remember from our first lesson in Part 1, there are special arithmetic operators for division.
Regular division:

4.2

To return only the whole integer:

In [544]:
To return only the whole integer:

4

To return only the remainder:

In [547]:
To return only the remainder:

1

There is also a built-in function to return both the integer and the remainder:

In [550]:
There is also a built-in function to return both the integer and the remainder:

(4, 1)

The result of the function `divmod()` is a tuple!

The function for calculating a T-test for the means of two independent samples returns a fancy tuple with two items. It is found in the **scipy** module.

In [552]:
The function for calculating a T-test for the means of two independent samples returns a fancy tuple with two items. It is found in the **scipy** module.

In [553]:
The function for calculating a T-test for the means of two independent samples returns a fancy tuple with two items. It is found in the **scipy** module.

In [554]:
The function for calculating a T-test for the means of two independent samples returns a fancy tuple with two items. It is found in the **scipy** module.

TtestResult(statistic=-1.6991019936393787, pvalue=0.11140195153800304, df=14.0)

This is a very fancy tuple, with keywords, but it is still a tuple.
You can index a tuple to get the info you need:

In [559]:
This is a very fancy tuple, with keywords, but it is still a tuple.
You can index a tuple to get the info you need:

-1.6991019936393787
0.11140195153800304

**You can always change a tuple to a list to make it easier to work with**:

In [562]:
**You can always change a tuple to a list to make it easier to work with**:

[-1.6991019936393787, 0.11140195153800304]

## 2.18 Sets

**Sets are like unordered lists with no duplicate values.**

They are great for removing duplicates from lists:

In [567]:
They are great for removing duplicates from lists:

{10, 4}

You can change them back to lists in the same line of code to quickly remove duplicates from a list:

In [570]:
You can change them back to lists in the same line of code to quickly remove duplicates from a list:

[10, 4]

Sets are designated by curly brackets (Python knows it's not a dictionary if you don't include any colons inside), or just by using the set`()` function on a list:

In [573]:
Sets are designated by curly brackets (Python knows it's not a dictionary if you don't include any colons inside), or just by using the set`()` function on a list:

{8, 9, 10}

In [575]:
Sets are designated by curly brackets (Python knows it's not a dictionary if you don't include any colons inside), or just by using the set`()` function on a list:

{8, 9, 10}

## Exercise: sets

Store the following list. This is a list of birds you observed from your window.

In [579]:
Store the following list. This is a list of birds you observed from your window.

How many total birds did you observe? Write code to find the length of the `bird_obs` list:

In [582]:
How many total birds did you observe? Write code to find the length of the `bird_obs` list:

25

In [ ]:
How many total birds did you observe? Write code to find the length of the `bird_obs` list:

How many different types of birds did you observe? Write code to turn the `bird_obs` list into a set, and then find the length of that set. Bonus if you can do it in one line of code:

In [584]:
How many different types of birds did you observe? Write code to turn the `bird_obs` list into a set, and then find the length of that set. Bonus if you can do it in one line of code:

8

Which different bird types did you see? Turn the `bird_obs` list into a set, and loop through it, printing out each bird type:

In [586]:
Which different bird types did you see? Turn the `bird_obs` list into a set, and loop through it, printing out each bird type:

Blue Jay
European Starling
Mourning Dove
Northern Cardinal
Song Sparrow
Red-winged Blackbird
American Robin
American Crow

## 2.19 Ranges

Another Python collection! A range is created by the `range()` function. It is used to create a collection of integers in order so that you can loop through it.

The `range()` function takes 2 or 3 arguments: 
- which integer to start with
- which integer to end with
- how many integers to iterate by between numbers. *If you do not provide the third argument, the range will iterate by 1.*

If you run the function alone, it will return the range object:

In [588]:
If you run the function alone, it will return the range object:

range(1, 10, 2)

This isn't very useful. But, if you loop through the range object, you can do something with each number:

In [591]:
This isn't very useful. But, if you loop through the range object, you can do something with each number:

1
3
5
7
9

**You can also change the range object into a list to work with it**:

In [594]:
**You can also change the range object into a list to work with it**:

[1, 3, 5, 7, 9]

*Note: `range()` does not work with floats, only integers. To create a range of floats, you will need to import the module numpy.*

Like Python indexing, the stop position is **exclusive** of the number passed as the stop argument:

In [598]:
Like Python indexing, the stop position is **exclusive** of the number passed as the stop argument:

1
2
3
4
5
6
7
8
9
10

## Exercise: range

Write a for loop to print every 20th number from 0 to 400.

In [603]:
Write a for loop to print every 20th number from 0 to 400.

0
20
40
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400

## 2.20 Dictionaries

Earlier, we practiced looping through fictional characters from Avengers, Star Wars, and Moana. But how did the computer know who was in which movie, or who could fly?

A dictionary is **a collection of *key: value* pairs.** 
- Dictionaries are surrounded by curly brackets {}
- **key: value pairs** inside the dictionary are separated by commas
- In each **key: value pair**, the key and value are separated by a colon :
- The key must always be a string
- The value can be any object

Here's a dictionary of heights, in inches. The keys are people's names and the values are integers:

In [608]:
Here's a dictionary of heights, in inches. The keys are people's names and the values are integers:

`dict` *is a common abbreviation for a dictionary in Python.*

This dictionary has info about someone's mom. The keys are trait categories and the values are a mix of integers and strings:

In [612]:
This dictionary has info about someone's mom. The keys are trait categories and the values are a mix of integers and strings:

This dictionary contains results of an experiment. The keys are the names of the test runs and the values are lists of floats:

In [615]:
This dictionary contains results of an experiment. The keys are the names of the test runs and the values are lists of floats:

*If a dictionary is long, you can write it on multiple lines, just like a list.*

## 2.21 Indexing a dictionary

In [619]:
## 2.21 Indexing a dictionary

{'Charlie': [90, 96, 89, 79], 'Tony': [99, 98, 96, 93], 'Suman': [85, 88, 83, 87], 'Yuvie': [66, 76, 80, 62], 'May': [97, 94, 89, 91]}

**Unlike lists, dictionaries are indexed by the name of the key. They cannot be indexed by position in the dictionary.** In the latest versions of Python, dictionaries are saved in order, but the purpose of a dictionary isn't to keep entries in numerical order - would you ever need to know what the 110th word in the Oxford English Dictionary is?

In [622]:
**Unlike lists, dictionaries are indexed by the name of the key. They cannot be indexed by position in the dictionary.** In the latest versions of Python, dictionaries are saved in order, but the purpose of a dictionary isn't to keep entries in numerical order - would you ever need to know what the 110th word in the Oxford English Dictionary is?

[99, 98, 96, 93]

In [624]:
**Unlike lists, dictionaries are indexed by the name of the key. They cannot be indexed by position in the dictionary.** In the latest versions of Python, dictionaries are saved in order, but the purpose of a dictionary isn't to keep entries in numerical order - would you ever need to know what the 110th word in the Oxford English Dictionary is?

KeyError: 3

To index something inside a value, first index the key, then the position in the value. In our `grade_dict` example, the values are lists, so to index Tony's last grade:

In [627]:
To index something inside a value, first index the key, then the position in the value. In our `grade_dict` example, the values are lists, so to index Tony's last grade:

93

### Exercise: Creating and indexing dictionaries

Create a dictionary called `favorites`. The keys should be "color", "food", and "song". The values should be your favorite color, food, and song.

In [631]:
Create a dictionary called `favorites`. The keys should be "color", "food", and "song". The values should be your favorite color, food, and song.

Write code to index your favorite song:

In [633]:
Write code to index your favorite song:

'The Wheels on the Bus'

Write code to index the third letter of your favorite food.

In [635]:
Write code to index the third letter of your favorite food.

'r'

## 2.22 Adding an entry to a dictionary

You don't have to use a function to add to a dictionary. Just **index** a new key and **assign** it a value:

Let's look at the `grade_dict` as it is now, and then add a new student.

In [637]:
Let's look at the `grade_dict` as it is now, and then add a new student.

{'Charlie': [90, 96, 89, 79], 'Tony': [99, 98, 96, 93], 'Suman': [85, 88, 83, 87], 'Yuvie': [66, 76, 80, 62], 'May': [97, 94, 89, 91]}

In [639]:
Let's look at the `grade_dict` as it is now, and then add a new student.

In [641]:
Let's look at the `grade_dict` as it is now, and then add a new student.

{'Charlie': [90, 96, 89, 79], 'Tony': [99, 98, 96, 93], 'Suman': [85, 88, 83, 87], 'Yuvie': [66, 76, 80, 62], 'May': [97, 94, 89, 91], 'Ben': [60, 57, 63]}

If the item already exists in the dictionary, you will overwrite it:

In [644]:
If the item already exists in the dictionary, you will overwrite it:

{'Charlie': [90, 96, 89, 79], 'Tony': [99, 98, 96, 93], 'Suman': [85, 88, 83, 87], 'Yuvie': [66, 76, 80, 62], 'May': [97, 94, 89, 91], 'Ben': [82, 88, 90]}

You should always be careful that your dictionary keys are unique.

### Exercise: Adding to dictionaries

Add a new key:value pair to your `favorites` dictionary. The key could be tv_show, movie, book, or anything else you'd like to add.

In [651]:
Add a new key:value pair to your `favorites` dictionary. The key could be tv_show, movie, book, or anything else you'd like to add.

In [653]:
Add a new key:value pair to your `favorites` dictionary. The key could be tv_show, movie, book, or anything else you'd like to add.

{'color': 'blue', 'food': 'strawberries', 'song': 'The Wheels on the Bus', 'book': 'Jamberry'}

In [ ]:
Add a new key:value pair to your `favorites` dictionary. The key could be tv_show, movie, book, or anything else you'd like to add.

## 2.23 Looping through a dictionary

Let's try to loop through a dictionary the same way we would loop through a list:

In [655]:
Let's try to loop through a dictionary the same way we would loop through a list:

Charlie
Tony
Suman
Yuvie
May
Ben

If you have an updated version of Python 3, it will print out the keys in the order you gave them when you first created the dictionary. If you have a slightly older version of Python 3, it might give you an error.
In either case, this way doesn't allow us to loop through the values or loop through both the keys and the values. 
Python has dictionary methods that will give you a list of just the `keys` or just the `values`:

In [658]:
If you have an updated version of Python 3, it will print out the keys in the order you gave them when you first created the dictionary. If you have a slightly older version of Python 3, it might give you an error.
In either case, this way doesn't allow us to loop through the values or loop through both the keys and the values. 
Python has dictionary methods that will give you a list of just the `keys` or just the `values`:

dict_keys(['Charlie', 'Tony', 'Suman', 'Yuvie', 'May', 'Ben'])

In [660]:
If you have an updated version of Python 3, it will print out the keys in the order you gave them when you first created the dictionary. If you have a slightly older version of Python 3, it might give you an error.
In either case, this way doesn't allow us to loop through the values or loop through both the keys and the values. 
Python has dictionary methods that will give you a list of just the `keys` or just the `values`:

dict_values([[90, 96, 89, 79], [99, 98, 96, 93], [85, 88, 83, 87], [66, 76, 80, 62], [97, 94, 89, 91], [82, 88, 90]])

Our grade_dict dictionary values are lists, so we get a list of lists.

We can loop through a list! Let's be more explicit and tell the computer that we want to loop through only the keys by adding the `keys()` method to the end of our dictionary:

In [664]:
We can loop through a list! Let's be more explicit and tell the computer that we want to loop through only the keys by adding the `keys()` method to the end of our dictionary:

Charlie
Tony
Suman
Yuvie
May
Ben

Or we can loop through the values:

In [667]:
Or we can loop through the values:

[90, 96, 89, 79]
[99, 98, 96, 93]
[85, 88, 83, 87]
[66, 76, 80, 62]
[97, 94, 89, 91]
[82, 88, 90]

Remember that we can give our temporary variable any name we want in our for loop. This is commonly used:

In [670]:
Remember that we can give our temporary variable any name we want in our for loop. This is commonly used:

Charlie
Tony
Suman
Yuvie
May
Ben

In [672]:
Remember that we can give our temporary variable any name we want in our for loop. This is commonly used:

[90, 96, 89, 79]
[99, 98, 96, 93]
[85, 88, 83, 87]
[66, 76, 80, 62]
[97, 94, 89, 91]
[82, 88, 90]

But it's also good to use more appropriate variable names:

In [675]:
But it's also good to use more appropriate variable names:

Charlie
Tony
Suman
Yuvie
May
Ben

In [677]:
But it's also good to use more appropriate variable names:

[90, 96, 89, 79]
[99, 98, 96, 93]
[85, 88, 83, 87]
[66, 76, 80, 62]
[97, 94, 89, 91]
[82, 88, 90]

### Exercise: Looping through a dictionary

Write code to loop through the keys of your favorites dictionary. Print out each key.

In [679]:
Write code to loop through the keys of your favorites dictionary. Print out each key.

color
food
song
book

Write code to loop through the values of your favorites dictionary. Print out each value.

In [681]:
Write code to loop through the values of your favorites dictionary. Print out each value.

blue
strawberries
The Wheels on the Bus
Jamberry

There is also a method function for returning both the keys and the values:

In [683]:
There is also a method function for returning both the keys and the values:

dict_items([('Charlie', [90, 96, 89, 79]), ('Tony', [99, 98, 96, 93]), ('Suman', [85, 88, 83, 87]), ('Yuvie', [66, 76, 80, 62]), ('May', [97, 94, 89, 91]), ('Ben', [82, 88, 90])])

The `.items()` method returns a list with one tuple for each key-value pair. 
We can also loop through the `.items()` tuples, but we have to include **two temporary variables** in our `for` loop statement instead of one:

In [686]:
The `.items()` method returns a list with one tuple for each key-value pair. 
We can also loop through the `.items()` tuples, but we have to include **two temporary variables** in our `for` loop statement instead of one:

Charlie
[90, 96, 89, 79]
Tony
[99, 98, 96, 93]
Suman
[85, 88, 83, 87]
Yuvie
[66, 76, 80, 62]
May
[97, 94, 89, 91]
Ben
[82, 88, 90]

In [688]:
The `.items()` method returns a list with one tuple for each key-value pair. 
We can also loop through the `.items()` tuples, but we have to include **two temporary variables** in our `for` loop statement instead of one:

Charlie
[90, 96, 89, 79]
Tony
[99, 98, 96, 93]
Suman
[85, 88, 83, 87]
Yuvie
[66, 76, 80, 62]
May
[97, 94, 89, 91]
Ben
[82, 88, 90]

### Exercise: Looping through a dictionary, both keys and values

Write code to loop through both the keys and values of your favorites dictionary. Print out a full sentence for each favorite, like "My favorite color is purple."

In [692]:
Write code to loop through both the keys and values of your favorites dictionary. Print out a full sentence for each favorite, like "My favorite color is purple."

My favorite color is blue.
My favorite food is strawberries.
My favorite song is The Wheels on the Bus.
My favorite book is Jamberry.

## 2.24 Nested loops
Since our values are list objects, we can also use a **nested loop** to loop through both the dictionary and the grade lists:

In [694]:
## 2.24 Nested loops
Since our values are list objects, we can also use a **nested loop** to loop through both the dictionary and the grade lists:

Charlie
90
96
89
79
Tony
99
98
96
93
Suman
85
88
83
87
Yuvie
66
76
80
62
May
97
94
89
91
Ben
82
88
90

That code is called a **nested loop** - a loop inside a loop!

### Exercise: Nested loop

Run the cell below to store the `nicknames` dictionary. The keys are the full names, and the values are the nicknames.

In [699]:
Run the cell below to store the `nicknames` dictionary. The keys are the full names, and the values are the nicknames.

Write a nested loop to print out each letter in each person's nickname:

In [702]:
Write a nested loop to print out each letter in each person's nickname:

C
h
a
r
l
i
e
T
o
n
y
S
u
m
a
n
Y
u
v
i
e
M
a
y
B
e
n
K
e
e
s
h
a

In [ ]:
Write a nested loop to print out each letter in each person's nickname:

*Hint: You must first decide if you need to loop through the keys, the values, or both. Do you need both to get the job done, or only the keys, or only the values?*

## 2.25 Filtering a dictionary
Just like we did with a list, we will want to combine a for loop with an if statement (or an if/elif/else statement).
Let's practice with our `nicknames` dictionary. Some of the nicknames are the same as the full names. Let's loop through the dictionary. If the person has a nickname that is different than their full name, we will print out a sentence like "Catherine goes by Katie." If they do not have a different nickname, we will print out a sentence like "Kelsey does not have a nickname."

In [704]:
## 2.25 Filtering a dictionary
Just like we did with a list, we will want to combine a for loop with an if statement (or an if/elif/else statement).
Let's practice with our `nicknames` dictionary. Some of the nicknames are the same as the full names. Let's loop through the dictionary. If the person has a nickname that is different than their full name, we will print out a sentence like "Catherine goes by Katie." If they do not have a different nickname, we will print out a sentence like "Kelsey does not have a nickname."

In [706]:
## 2.25 Filtering a dictionary
Just like we did with a list, we will want to combine a for loop with an if statement (or an if/elif/else statement).
Let's practice with our `nicknames` dictionary. Some of the nicknames are the same as the full names. Let's loop through the dictionary. If the person has a nickname that is different than their full name, we will print out a sentence like "Catherine goes by Katie." If they do not have a different nickname, we will print out a sentence like "Kelsey does not have a nickname."

Charles goes by Charlie.
Anthony goes by Tony.
Suman does not have a nickname.
Yuval goes by Yuvie.
May-Lin goes by May.
Benjamin goes by Ben.
Keesha does not have a nickname.

### Exercise: Filtering dictionaries

Here's an example dictionary. Run the cell below:

In [710]:
Here's an example dictionary. Run the cell below:

Using `hero_dict`, write a for loop/if statement to print the name of all of the characters in Star Wars:

In [713]:
Using `hero_dict`, write a for loop/if statement to print the name of all of the characters in Star Wars:

Finn
Princess Leia

OR

In [715]:
OR

Finn
Princess Leia

## 2.26 Adding key:value pairs to an empty dictionary

Yesterday we learned how to loop through a list and add items to a new empty list. We can also do that with dictionaries.
We will work with the grade_dict we used earlier:

In [718]:
Yesterday we learned how to loop through a list and add items to a new empty list. We can also do that with dictionaries.
We will work with the grade_dict we used earlier:

{'Charlie': [90, 96, 89, 79], 'Tony': [99, 98, 96, 93], 'Suman': [85, 88, 83, 87], 'Yuvie': [66, 76, 80, 62], 'May': [97, 94, 89, 91], 'Ben': [82, 88, 90]}

**LOGIC** Here we will create a new dictionary from the data in the grades_dict. For the new dictionary, the keys will be the students' names and the values will be their final score for the class. The final score will be calculated as the mean of all the scores in their grade list. We can use the mean function from the statistics package.

In [721]:
**LOGIC** Here we will create a new dictionary from the data in the grades_dict. For the new dictionary, the keys will be the students' names and the values will be their final score for the class. The final score will be calculated as the mean of all the scores in their grade list. We can use the mean function from the statistics package.

First, we create an empty dictionary. Next, we loop through the old dictionary, calculate each person's final grade, and add them to the new dictionary:

In [724]:
First, we create an empty dictionary. Next, we loop through the old dictionary, calculate each person's final grade, and add them to the new dictionary:

{'Charlie': 88.5, 'Tony': 96.5, 'Suman': 85.75, 'Yuvie': 71, 'May': 92.75, 'Ben': 86.66666666666667}

We can make the dictionary look more consistent by rounding all the numbers to two places after the decimal point:

In [727]:
We can make the dictionary look more consistent by rounding all the numbers to two places after the decimal point:

{'Charlie': 88.5, 'Tony': 96.5, 'Suman': 85.75, 'Yuvie': 71, 'May': 92.75, 'Ben': 86.67}

The round function won't include trailing zeros, like on 96.5. We can make the dictionary look a little more consistent by changing the whole numbers, like 71, to floats:

In [730]:
The round function won't include trailing zeros, like on 96.5. We can make the dictionary look a little more consistent by changing the whole numbers, like 71, to floats:

{'Charlie': 88.5, 'Tony': 96.5, 'Suman': 85.75, 'Yuvie': 71.0, 'May': 92.75, 'Ben': 86.67}

## 2.27 List of dictionaries

Sometimes it is useful to have a list of dictionaries because that is how your data is best represented. You can index individual data points in the list or dictionaries, and you can loop through both levels.

In [734]:
Sometimes it is useful to have a list of dictionaries because that is how your data is best represented. You can index individual data points in the list or dictionaries, and you can loop through both levels.

**Indexing a list of dictionaries**
To return an individual dictionary, you use list indexing because each dictionary is an item in the list. What do you think this will return?

In [737]:
**Indexing a list of dictionaries**
To return an individual dictionary, you use list indexing because each dictionary is an item in the list. What do you think this will return?

{'name': 'Cylon', 'HW1': 10, 'HW2': 10, 'HW3': 10}

To return a value in one of the dictionaries, you first index the dictionary's place in the list, and then index the key in your key:value pair of interest. What do you think this will return?

In [740]:
To return a value in one of the dictionaries, you first index the dictionary's place in the list, and then index the key in your key:value pair of interest. What do you think this will return?

7

**Looping through a list of dictionaries**
**LOGIC** Let's print out a full sentence for each student. The sentence should report the sum of all the student's homework assignment grades.

It's often useful to first just print each item in a loop, to confirm that you know what you're looking at. I do this all the time when I code:

In [744]:
It's often useful to first just print each item in a loop, to confirm that you know what you're looking at. I do this all the time when I code:

{'name': 'Zygon', 'HW1': 10, 'HW2': 10, 'HW3': 10}
{'name': 'Vogon', 'HW1': 10, 'HW2': 10, 'HW3': 10}
{'name': 'Cylon', 'HW1': 10, 'HW2': 10, 'HW3': 10}
{'name': 'Mudokon', 'HW1': 7, 'HW2': 8, 'HW3': 6}

Then you can do more and slowly build up your loop:

In [747]:
Then you can do more and slowly build up your loop:

Zygon
Vogon
Cylon
Mudokon

In [749]:
Then you can do more and slowly build up your loop:

30
30
30
21

In [751]:
Then you can do more and slowly build up your loop:

Zygon scored 30 points on Homework
Vogon scored 30 points on Homework
Cylon scored 30 points on Homework
Mudokon scored 21 points on Homework

## 2.28 Hard coding
The code we just wrote is ok, but it wouldn't work if more than 3 homework assignments were added. Let's say you teach the same class next year and you want to reuse the code, only next year you give 4 homework assignments instead of 3.

When there are details in the code specific to your data, we say they are **hard coded**.
As a beginner, you will do a lot of hard coding to solve your problems, but if you ever want to reuse your scripts or share them with someone else, you will need to try to not hard code.

Instead, you can loop through the list and then loop through the dictionary (a **nested loop**). 
I've included **comments** in the code to explain what I'm doing. Comments start with a `#` and are ignored by the computer.

In [756]:
Instead, you can loop through the list and then loop through the dictionary (a **nested loop**). 
I've included **comments** in the code to explain what I'm doing. Comments start with a `#` and are ignored by the computer.

Zygon scored 30 points on Homework
Vogon scored 30 points on Homework
Cylon scored 30 points on Homework
Mudokon scored 21 points on Homework

**OR**

In [759]:
**OR**

Zygon scored 30 points on Homework
Vogon scored 30 points on Homework
Cylon scored 30 points on Homework
Mudokon scored 21 points on Homework

## 2.29 Dictionary of dictionaries

You can also format your data as a dictionary of dictionaries.

### Exercise: Indexing a nested dictionary

In [764]:
### Exercise: Indexing a nested dictionary

Use dictionary indexing to write code to return all of Cylon's grades:

In [768]:
Use dictionary indexing to write code to return all of Cylon's grades:

{'HW1': 10, 'HW2': 10, 'HW3': 10}

Use dictionary indexing to write code to return Vogon's score on HW2:

In [770]:
Use dictionary indexing to write code to return Vogon's score on HW2:

10

## Part 2 Quiz

Test yourself on what you learned in this part by completing the Part 2 Quiz. The Jupyter Notebook file is called "part2Quiz.ipynb" and is in the same folder as this notebook.

The quiz is self-graded - you do not need to turn anything in! The answer key is called "part2Quiz-answers.ipynb".

In [ ]:
The quiz is self-graded - you do not need to turn anything in! The answer key is called "part2Quiz-answers.ipynb".